name: Asignar UUIDs Condicionalmente a Múltiples JSON

on:
  push:
    paths:
      - 'LK/lichking.json'
      - 'Cata/cataclysm.json'
      - 'Panda/pandaria.json'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente si es necesario

jobs:
  assign-uuids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Necesario para permitir push

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Actualiza a la versión 20 para evitar la advertencia

      - name: Instalar dependencias
        run: npm install uuid

      - name: Ejecutar script para asignar UUIDs
        run: node assign-uuids.js

      - name: Configurar Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit y Push si hay cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add LK/lichking.json Cata/cataclysm.json Panda/pandaria.json
          git diff --cached --exit-code || git commit -m "Asignar UUIDs a objetos sin UUID"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} || { echo "Git push falló"; exit 1; }
