name: Asignar UUIDs Condicionalmente a Múltiples JSON

on:
  push:
    paths:
      - 'LK/lichking.json'
      - 'Cata/cataclysm.json'
      - 'Panda/pandaria.json'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente si es necesario

jobs:
  assign-uuids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para permitir push y crear ramas

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Actualiza a la versión 20 para evitar la advertencia

      - name: Instalar dependencias
        run: npm install uuid

      - name: Ejecutar script para asignar UUIDs
        run: node assign-uuids.js

      - name: Configurar Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit si hay cambios
        run: |
          git add LK/lichking.json Cata/cataclysm.json Panda/pandaria.json
          git diff --cached --exit-code || git commit -m "Asignar UUIDs a objetos sin UUID"

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Asignar UUIDs a objetos sin UUID"
          branch: assign-uuids-${{ github.run_id }}
          title: "Asignar UUIDs a objetos sin UUID"
          body: "Este Pull Request asigna UUIDs a los objetos en los archivos JSON."
          labels: automatic-uuid-assignment
          # reviewers: tu-usuario  # Opcional: Asigna revisores
