name: Asignar UUIDs a JSON

on:
  push:
    paths:
      - 'LK/lichking.json'
      - 'Cata/cataclysm.json'
      - 'Panda/pandaria.json'

jobs:
  assign-uuids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para permitir crear ramas

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install uuid

      - name: Ejecutar script para asignar UUIDs
        run: node assign-uuids.js

      - name: Commit y creación de Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Asignar UUIDs a objetos sin UUID"
          branch: assign-uuids-${{ github.run_id }}
          title: "Asignar UUIDs a JSON"
          body: "Este PR asigna UUIDs a los objetos en los archivos JSON."
